### PR TITLE
Initial Commit to Open-Source Repository

### PR DESCRIPTION
**Pull request by tylerwilding-wk**

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched keyword <code>BUILD_ARTIFACTS_VERACODE</code> in <code>workivabuild.Dockerfile</code> line(s) ['72'] added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by erikpetersen-wf** [comment]
+1

**Comment by tylerwilding-wk** [comment]
InfoSec review is not required for this PR to merge.

**Comment by tylerwilding-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
